### ISSUE TITLE
SOLID POD: Update `flutter_secure_storage` in pubspec.yaml

### ISSUE THREAD

**Issue by cdawei** [anusii/solidpod#245]
With Flutter 3.27.2 on Linux, there is a compile error
```
flutter_secure_storage_linux/linux/flutter_secure_storage_linux_plugin.cc:193:50: 
error: use of undeclared identifier 'APPLICATION_ID'
```
This issue is fixed in the lastest develop code in the [flutter_secure_storage](https://github.com/juliansteenbakker/flutter_secure_storage) repository, and it appears [the version with the fix](https://pub.dev/packages/flutter_secure_storage_linux) has been uploaded to pub.dev.

Please update the version of `flutter_secure_storage_linux` in `pubspec.yaml` and test if the above error is resolved.

If not, a workaround is to override the version of package `flutter_secure_storage_linux` in pubspec.yaml as reported in [this issue](https://github.com/juliansteenbakker/flutter_secure_storage/issues/829)
```
dependency_overrides:
  flutter_secure_storage_linux:
    git:
      url: https://github.com/juliansteenbakker/flutter_secure_storage.git
      ref: v9.2.4
      path: flutter_secure_storage_linux
```
